#  NumPy Arrays – Basics

## 1. What is a NumPy Array ?
- A NumPy array is a **multidimensional, homogeneous data structure**.
- Homogeneous → all elements have the same datatype (int, float, etc.).
- Faster and more memory-efficient than Python lists.

In [18]:
# For Example ,

# Creating Arrays
import numpy as np
# From list
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [39]:
# Range of numbers
array1 = np.arange(0, 10, 4)
array1

array([0, 4, 8])

In [45]:
# Array of zeros
array2 = np.zeros((5, 6))
array2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [51]:
# Array of ones
array3 = np.ones((5, 3))
array3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
# Linearly spaced numbers
array4 = np.linspace(1, 6, 5)
array4

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

# Array Properties

In [86]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", array.shape)     

Shape: (2, 3)


In [88]:
print("Dimensions:", array.ndim)

Dimensions: 2


In [90]:
print("Size:", array.size)

Size: 6


In [92]:
print("Data type:", array.dtype)

Data type: int32


# Mathematical Operations 

In [97]:
# Addition
Num1 = np.array([29, 82, 10, 45])
Num2 = np.array([53, 60, 80, 39])
print(Num1 + Num2)   

[ 82 142  90  84]


In [99]:
# Substraction
Num1 = np.array([29, 82, 10, 45])
Num2 = np.array([53, 60, 80, 39])
print(Num1 - Num2)  

[-24  22 -70   6]


In [101]:
# Multiplication
Num1 = np.array([29, 82, 10, 45])
Num2 = np.array([53, 60, 80, 39])
print(Num1 * Num2) 

[1537 4920  800 1755]


In [105]:
# Division
Num1 = np.array([29, 82, 10, 45])
Num2 = np.array([53, 60, 80, 39])
print(Num1 / Num2) 

[0.54716981 1.36666667 0.125      1.15384615]


In [107]:
# Exponentiation
Num1 = np.array([29, 82, 10, 45])
Num2 = np.array([53, 60, 80, 39])
print(Num1 ** Num2) 

[-1595911571           0           0  -984163387]


# Indexing and Slicing

In [112]:
# 1 Diamentional array
Array = np.array([10, 20, 30, 40, 50])
print(Array[0])     
print(Array[-1])    
print(Array[1:4])   
print(Array[::2])   

10
50
[20 30 40]
[10 30 50]


In [116]:
# 2 Diamentional array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[0, 0])  
print(matrix[1, :])   
print(matrix[:, 2])  

1
[4 5 6]
[3 6]


In [122]:
# 3 Diamentional array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[0, 0])  
print(matrix[1, :])   
print(matrix[:, 2])  

1
[4 5 6]
[3 6 9]


# Functions 

In [131]:
Fun = np.array([1,2,3,4,5])
print(np.sum(Fun))  

15


In [133]:
print(np.mean(Fun))  

3.0


In [135]:
print(np.max(Fun))   

5


In [137]:
print(np.min(Fun)) 

1


In [139]:
print(np.sqrt(Fun)) 

[1.         1.41421356 1.73205081 2.         2.23606798]
